# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:02
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.get_file_payments)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
