# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180319_1747'),
        ('core', '0004_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurAdvantages',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='ProgramingSections',
        ),
        migrations.DeleteModel(
            name='Technologies',
        ),
    ]
