# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171021_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
