# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171021_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='foundation_year',
            field=models.DateTimeField(null=True),
        ),
    ]
