# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_cooperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='client',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='company',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='company',
            field=models.ManyToManyField(to='users.Company'),
        ),
    ]
