# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171031_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='client',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='company',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
    ]
