# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payments'),
        ('users', '0022_auto_20171201_1416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycategories',
            unique_together=set([('company', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='companytechnicalstack',
            unique_together=set([('technology', 'company')]),
        ),
    ]
