# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20171227_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': 'Search history'},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
