# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20171227_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytechnicalstack',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
