# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_companytechnicalstack_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytechnicalstack',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
