# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20171228_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
