# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180208_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
