# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20180214_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytechnicalstack',
            name='border_color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
