# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_companytechnicalstack_border_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycategories',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='companycategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='companycategories',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyprojects',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyprojectsimages',
            name='project',
        ),
        migrations.RemoveField(
            model_name='companyprojectstechnologies',
            name='project',
        ),
        migrations.RemoveField(
            model_name='companyprojectstechnologies',
            name='technology',
        ),
        migrations.AlterUniqueTogether(
            name='companytechnicalstack',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='companytechnicalstack',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companytechnicalstack',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specificfeatures',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='CompanyCategories',
        ),
        migrations.DeleteModel(
            name='CompanyProjects',
        ),
        migrations.DeleteModel(
            name='CompanyProjectsImages',
        ),
        migrations.DeleteModel(
            name='CompanyProjectsTechnologies',
        ),
        migrations.DeleteModel(
            name='CompanyTechnicalStack',
        ),
        migrations.DeleteModel(
            name='Cooperation',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='SpecificFeatures',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
