# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20180327_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TestQuestionAnswers')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Learner')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Test')),
            ],
            options={
                'verbose_name_plural': 'TestResults',
            },
        ),
    ]
