# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_testresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.TestQuestion'),
            preserve_default=False,
        ),
    ]
