# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_testanalysistypeyesno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSandxak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TestSandxak',
            },
        ),
        migrations.AddField(
            model_name='testquestion',
            name='sandxak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TestSandxak'),
        ),
    ]
