# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20180420_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAnalysisResults',
        ),
        migrations.DeleteModel(
            name='TestAnalysisTypeYesNo',
        ),
    ]
