# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20180420_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yes_no_rate_start', models.IntegerField()),
                ('yes_no_rate_end', models.IntegerField()),
                ('type_two_rate_end', models.IntegerField()),
                ('type_two_rate_start', models.IntegerField()),
                ('analysis', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TestAnalysisTypeYesNo',
            },
        ),
    ]
