# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_testanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanalysis',
            options={'verbose_name_plural': 'Test Analysis'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name_plural': 'Test Question'},
        ),
        migrations.AlterModelOptions(
            name='testquestionanswers',
            options={'verbose_name_plural': 'Test Question Answer'},
        ),
        migrations.AlterModelOptions(
            name='testresults',
            options={'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterModelOptions(
            name='testsandxak',
            options={'verbose_name_plural': 'Test Sandxak'},
        ),
    ]
